### ISSUE TITLE
Please keep the GPLv3 license in tact with the source code and derivatives

### ISSUE THREAD

**Issue by galexmanuel** [jling-NM/CACTI#1]
HI,
I am the original developer of the CACTI software which I wrote in the summer after my junior year at UNM.  

The source code, any future revisions, versions and derivatives are licensed under the [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html).  All source files must be labeled as such, and a copy of the license must be distributed with source code and libraries and executables derived from the code.  Additionally, any and all derivative works must explicitly identify their revisions. 
 Please take steps to ensure your revisions comply with the source code licensing. 

Thanks for using and modifying the CACTI code to your needs.

Thanks,
Alex Manuel

**Comment by jling-NM** [comment]
License text has been included where missing. A revision statement has been added to the README.

**Comment by galexmanuel** [comment]
Thanks for the quick turnaround!  BTW, your FLAC tool is pretty cool.
Thanks,
Alex
