### ISSUE TITLE
Please keep the GPL v3 license intact with all source code and derivatives

### ISSUE THREAD

**Issue by galexmanuel** [jling-NM/CACTI#2]
The license to the original CACTI source is the GPL v3.  By law, any and all derivative source code must provide and maintain this license intact.  Regardless of the changes you have made this project is still built upon intellectual property I created and licensed under the GPL v3.  Thus any and all derivative works, any source code that touches uses or used this original code in anyway is subject to the GPL v3.  As this sits now it violates the license, and is actionable.
https://www.gnu.org/licenses/gpl-violation.html
Please maintain the license with the source code and make it and the source code openly available in order to comply with the law.

**Comment by galexmanuel** [comment]
If this isn't immediately remedied, I will report it to the FSF lawyers.

**Comment by galexmanuel** [comment]
For reference, this is the GPL v3 details: https://www.gnu.org/licenses/gpl-3.0.en.html

A “covered work” means either the unmodified Program or a work based on the Program.

**Comment by jling-NM** [comment]
It is not our intent to change or misrepresent the GPL v3 license. Thank you for the link to the GPL v3 license details. I will review this to make sure we are in compliance.

**Comment by jling-NM** [comment]
A new LICENSE has been added which includes the GPLv3 text. 
A new README.md file has been added which also includes the license status of the project.
A couple of XML and CSS files now include the copyright notice at the top to match what was already in the source files.
